### ISSUE TITLE
Android build failed, references BeaconBroadcastPackage

### ISSUE THREAD

**Issue by pporche87** [williamtran29/react-native-ibeacon-simulator#5]
I get this build error when I download the ibeacon package. This only happens on the android side. 

`/node_modules/react-native-ibeacon-simulator/android/src/main/java/com/ibeacon/simulator/BeaconBroadcastPackage.java:20: error: method does not override or implement a method from a supertype`

Any thoughts?

**Comment by nathan815** [comment]
Were you ever able to fix this?
